/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.dronworks;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Product product = new Product();
        product.setName("app");
        product.setDescription("java app");
        product.setPrice("100");
        System.out.println(product.getName() + " " + product.getDescription() + " " + product.getPrice());
    }
}
